### consulta de clientes
GET http://www.sexto2026compu.com/clientes
### modificar clientes
PUT http://www.sexto2026compu.com/clientes/1
Content-Type: application/json

{
    "ci":1234678,
    "nombre":"Juan",
    "apellidos":"Perez",
    "direccion":"Calle Falsa 123",
    "telefono":123456789
}

### agregar clientes
POST http://www.sexto2026compu.com/clientes
Content-Type: application/json

{
    "ci":12345678,
    "nombre":"Juan",
    "apellidos":"Perez",
    "direccion":"Calle Falsa 123",
    "telefono":123456789
}

### eliminar cliente
DELETE http://www.sexto2026compu.com/clientes/1
