### consulta de pedido
GET http://www.sexto2026compu.com/pedido
### modificar pedido
PUT http://www.sexto2026compu.com/pedido/1
Content-Type: application/json

{
    "cod_cliente":1,
    "fecha":"2024-06-01",
    "estado":"procesand"
}
### agregar pedido
POST http://www.sexto2026compu.com/pedido
Content-Type: application/json

{
    "cod_cliente":1,
    "fecha":"2024-06-01",
    "estado":"procesando"
}

### eliminar pedido
DELETE http://www.sexto2026compu.com/pedido/1
