### consulta de productos
GET http://www.sexto2026compu.com/productos

### modificar productos
PUT http://www.sexto2026compu.com/productos/1

{
    "codbarras":4719331302840,
    "descripcion":"Laptop ASUS Vivobook 15 Core i5 16GB RAM 512GB SSD",
    "precio_unitario":7996.00,
    "stock":11
} 
### agregar productos
POST http://www.sexto2026compu.com/productos

{
    "codbarras":471543784458,
    "descripcion":"oh pc gamer",
    "precio_unitario":12576.00,
    "stock":32
}

### agregar productos con datos faltantes
POST http://www.sexto2026compu.com/productos

{
    "codbarras":471543784458,
    "descripcion":"oh pc gamer",
    "precio_unitario":12576.00,
    "stock":32
}

### eliminar productos
DELETE http://www.sexto2026compu.com/productos/6
