### consulta de proveedores
GET http://www.sexto2026compu.com/proveedores
### modificar proveedores
PUT http://www.sexto2026compu.com/proveedores/1
Content-Type: application/json

{
    "ci":12345678,
    "nombre":"Pedronosque",
    "apellidos":"abalayavu"
}

### eliminar proveedor
DELETE http://www.sexto2026compu.com/proveedores/1
### agregar proveedores
POST http://www.sexto2026compu.com/proveedores
Content-Type: application/json

{
    "ci":12345678,
    "nombre":"Pedronosque",
    "apellidos":"abalayavu"
}
