### consulta de proveedor_producto
GET http://www.sexto2026compu.com/proveedor_producto
### modificar proveedor_producto
PUT http://www.sexto2026compu.com/proveedor_producto/1

{
    "cod_proveedor":1,
    "cod_producto":1
}
### agregar proveedor_producto
POST http://www.sexto2026compu.com/proveedor_producto

{
    "cod_proveedor":1,
    "cod_producto":1
}